@startuml

title "Jvm Thread Struct"

rectangle "堆\nHeap" as Heap #red;text:white

card "线程A" as ta {
    rectangle "程序计数器\nProgram Counter Register" as PC #aaaaaa;text:black
    stack "本地方法栈\nNative Method Stack" as NativeMethodStack #aaaaaa;text:black
    stack "虚拟机栈\nJava Virtual Machine Stack" as Stack #aaaaaa;text:black
    PC -[hidden]-> Stack
    Stack -[hidden]-> NativeMethodStack
}

card "线程B" as tb {
    rectangle "程序计数器\nProgram Counter Register" as PCb #aaaaaa;text:black
    stack "本地方法栈\nNative Method Stack" as NativeMethodStackb #aaaaaa;text:black
    stack "虚拟机栈\nJava Virtual Machine Stack" as Stackb #aaaaaa;text:black
    PCb -[hidden]-> Stackb
    Stackb -[hidden]-> NativeMethodStackb
}

card "线程C" as tc {
    rectangle "程序计数器\nProgram Counter Register" as PCc #aaaaaa;text:black
    stack "本地方法栈\nNative Method Stack" as NativeMethodStackc #aaaaaa;text:black
    stack "虚拟机栈\nJava Virtual Machine Stack" as Stackc #aaaaaa;text:black
    PCc -[hidden]-> Stackc
    Stackc -[hidden]-> NativeMethodStackc
}

rectangle "方法区\nMethod Area" as MethodArea #red;text:white

ta -up-> Heap
tb -up-> Heap
tc -up-> Heap
ta -down-> MethodArea
tb -down-> MethodArea
tc -down-> MethodArea
NativeMethodStackb -[hidden]-> MethodArea

@enduml