@startuml

title HotSpot JVM Architecture

collections "Class File" as ClassFile

rectangle "类加载子系统\nClass Loader Subsystem" as ClassLoaderSubsystem

ClassFile -right-> ClassLoaderSubsystem #666666;line.bold

node "运行时数据区\nRuntime Data Area" as RuntimeDataArea {
    rectangle "方法区\nMethod Area" as MethodArea #red;text:white
    rectangle "程序计数器\nProgram Counter Register" as PC #aaaaaa;text:black
    rectangle "本地方法栈\nNative Method Stack" as NativeMethodStack #aaaaaa;text:black
    rectangle "堆\nHeap" as Heap #red;text:white
    rectangle "虚拟机栈\nJava Virtual Machine Stack" as Stack #aaaaaa;text:black
}

ClassLoaderSubsystem -down-> RuntimeDataArea #666666;line.bold
RuntimeDataArea -up-> ClassLoaderSubsystem #666666;line.bold

rectangle "执行引擎\nExecution Engine" as ExecutionEngine #magenta;line:blue;line.dotted;text:white

RuntimeDataArea -down-> ExecutionEngine #666666;line.bold
ExecutionEngine -up-> RuntimeDataArea #666666;line.bold

rectangle "本地方法接口\nNative Method Interface" as NativeMethodInterface #00000000;line:black;line.dotted;text:black

RuntimeDataArea -down-> NativeMethodInterface #666666;line.bold
NativeMethodInterface -up-> RuntimeDataArea #666666;line.bold

ExecutionEngine -right-> NativeMethodInterface #666666;line.bold
NativeMethodInterface -left-> ExecutionEngine #666666;line.bold

rectangle "本地方法库\nNative Method Libraries" as NativeMethodLibraries #00000000;line:00000000;line.dotted;text:black

NativeMethodInterface -left-> NativeMethodLibraries #666666;line.bold
NativeMethodLibraries -left-> NativeMethodInterface #666666;line.bold

@enduml