@startuml

skinparam state {
  StartColor Green
}

state CustomClassLoader ##[dotted]green : 自定义类加载器
state AppClassLoader ##[dotted]green : 系统类加载器
state PlatformClassLoader ##[dotted]green : 平台类加载器
state BootStrapClassLoader ##[dotted]green : 引导类加载器
note right of BootStrapClassLoader : "父类加载失败由子类处理"
note right of AppClassLoader : "父类加载失败由子类处理"
note right of PlatformClassLoader : "父类加载失败由子类处理"
note right of CustomClassLoader : "父类加载失败由子类处理"

[*] -up-> CustomClassLoader : 加载类
CustomClassLoader -up->  AppClassLoader : 向上委托
AppClassLoader -up->  PlatformClassLoader : 向上委托
PlatformClassLoader -up->  BootStrapClassLoader : 向上委托

@enduml